# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\mh-cbon\go-msi

# skip_non_tags: true

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1
  CHOCOKEY:
    secure: HRc9tf57V3c3dVyn8hvMkKeiwK2oyWvOSjNXembIAQctNx+GTGBBaHI3bh+8cIgy

# scripts that run after cloning repository
install:
  - ps: Write-Host "APPVEYOR_BUILD_VERSION=$env:APPVEYOR_BUILD_VERSION";
  - ps: Write-Host "APPVEYOR_REPO_TAG_NAME=$env:APPVEYOR_REPO_TAG_NAME";
  - ps: if (-not (Test-Path env:APPVEYOR_REPO_TAG_NAME)) { $env:APPVEYOR_REPO_TAG_NAME = '0.0.2' }
  - ps: ls env:APPVEYOR_REPO_TAG_NAME
  - curl -fsSL -o C:\wix310-binaries.zip http://static.wixtoolset.org/releases/v3.10.3.3007/wix310-binaries.zip
  - 7z x C:\wix310-binaries.zip -y -r -oC:\wix310
  - set PATH=C:\wix310;%PATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go get -u github.com/Masterminds/glide

# to run your custom scripts instead of automatic MSBuild
build_script:
  - glide install
  - set MYAPP=go-msi
  - set GOARCH=386
  - go build -o %MYAPP%.exe --ldflags "-X main.VERSION=%APPVEYOR_REPO_TAG_NAME%" main.go
  - .\go-msi.exe make --msi %APPVEYOR_BUILD_FOLDER%\%MYAPP%-%GOARCH%.msi --version %APPVEYOR_REPO_TAG_NAME% --arch %GOARCH%
  - set GOARCH=amd64
  - go build -o %MYAPP%.exe --ldflags "-X main.VERSION=%APPVEYOR_REPO_TAG_NAME%" main.go
  - .\go-msi.exe make --msi %APPVEYOR_BUILD_FOLDER%\%MYAPP%-%GOARCH%.msi --version %APPVEYOR_REPO_TAG_NAME% --arch %GOARCH%

after_deploy:
  - .\go-msi.exe choco --input %APPVEYOR_BUILD_FOLDER%\%MYAPP%-%GOARCH%.msi --version %APPVEYOR_REPO_TAG_NAME%
  - choco push -k="'%CHOCOKEY%'" %MYAPP%.%APPVEYOR_REPO_TAG_NAME%.nupkg

before_test:
  - ps: Start-FileDownload 'https://github.com/mh-cbon/changelog/releases/download/0.0.25/changelog-amd64.msi'
  - msiexec.exe /i changelog-amd64.msi /quiet
  - DEL /F changelog-amd64.msi
  - mkdir C:\go-msi\
  - set GOARCH=amd64
  - go build -o C:\go-msi\go-msi.exe --ldflags "-X main.VERSION=%APPVEYOR_REPO_TAG_NAME%" main.go
  - XCOPY /I /E templates C:\go-msi\templates
  - cd testing
  - glide install
  - go run testing\\main.go
  - cd ..

artifacts:
  - path: '*-386.msi'
    name: msi-x86
  - path: '*-amd64.msi'
    name: msi-x64

deploy:
  - provider: GitHub
    artifact: msi-x86, msi-x64
    draft: false
    prerelease: false
    desription: "Release %APPVEYOR_REPO_TAG_NAME%"
    auth_token:
      secure: WVMaMjrLzXN8YNcnFRfcucTYWtvoDeE/4b2TUGQBZDvv7u+ERBQ///z5Q8qYSt0L
    on:
      branch:
        - master
        - /v\d\.\d\.\d/
        - /\d\.\d\.\d/          # not so great solution found here
                                # http://help.appveyor.com/discussions/problems/3483-github-tag-push-doesnt-trigger-build
      appveyor_repo_tag: true   # deploy on tag push only
